### PR TITLE
New Theme

### PR DESCRIPTION
**Pull request by htcz0qtb**
test

### CODE REVIEW

**Comment by rickstaa** [comment]
# Automated Theme Preview
        
    
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
    
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.
  
    
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)
  
      
        
:heavy_check_mark: Theme PR does adhere to our guidelines.
        
## Test results
        
- :heavy_check_mark: test_pine
  
        
**Result:** :heavy_check_mark: All themes are valid.
        
        
## Details
        
          
### Test_pine theme preview
          
          
  
          
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>
  
          
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)
  
          
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Review by rickstaa — APPROVED** [review]
:x: Theme PR does not adhere to our guidelines.

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See 'Automated Theme Preview' above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See [Automated Theme Preview](https://api.github.com/repos/rickstaa/github-readme-stats/issues/comments/1258427600) above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See [Automated Theme Preview](https://github.com/rickstaa/github-readme-stats/pull/15#issuecomment-1258427600) above for more information.

**Review by rickstaa — APPROVED** [review]

**Comment by ElaminiSoulaimane** [comment]
test

**Review by rickstaa — APPROVED** [review]

**Pull request closed without merging**
